// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYMdUncz5CjiXFtLYCznV_2P3IlsUzv4I',
    appId: '1:218329886692:web:ec177362cacdba8f26a1f1',
    messagingSenderId: '218329886692',
    projectId: 'shopapp-2c914',
    authDomain: 'shopapp-2c914.firebaseapp.com',
    databaseURL: 'https://shopapp-2c914-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-2c914.appspot.com',
    measurementId: 'G-FQVN6DREZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWV9jlsVoLszWOO4whEwmCKIdAAAlHYcg',
    appId: '1:218329886692:android:435f51d7ff8cc99a26a1f1',
    messagingSenderId: '218329886692',
    projectId: 'shopapp-2c914',
    databaseURL: 'https://shopapp-2c914-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-2c914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV1eJ-I9M40sHMdVYh19ByY7F5a58kXhk',
    appId: '1:218329886692:ios:cabde375bbc3b29a26a1f1',
    messagingSenderId: '218329886692',
    projectId: 'shopapp-2c914',
    databaseURL: 'https://shopapp-2c914-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-2c914.appspot.com',
    iosClientId: '218329886692-rojljo3fkuoupclts7j51i04esssj7dl.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV1eJ-I9M40sHMdVYh19ByY7F5a58kXhk',
    appId: '1:218329886692:ios:590707fa64076b6426a1f1',
    messagingSenderId: '218329886692',
    projectId: 'shopapp-2c914',
    databaseURL: 'https://shopapp-2c914-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-2c914.appspot.com',
    iosClientId: '218329886692-o5arv6mjln4b9s4pu9bin4fd6fhnjhsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp.RunnerTests',
  );
}
